---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

install:
addons:
  apt:
    packages:
    - docker

script:
#Pull down ansible docker image for EL testing
  - sudo docker pull ansible/centos7-ansible:1.8
#Fire up ansible container
  - sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/ansible-aide:ro centos7-ansible:1.8
# Basic role syntax check
  - sudo docker exec "$(cat /tmp/container_id)" ansible-playbook /etc/ansible/roles/ansible-aide/test.yml -i /etc/ansible/ansible-aide/inventory --syntax-check
#Role run on localhost
  - sudo docker exec "$(cat /tmp/container_id)" ansible-playbook /etc/ansible/roles/ansible-aide/test.yml -i /etc/ansible/roles/ansible-aide/inventory --connection=local
  - sudo docker stop "$(cat /tmp/container_id)"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
